-- GENERATED by scripts/gen-money-mirror-test.mjs from supabase/tests/fixtures/money-conversion-cases.json.
-- Do not edit by hand. Mirrors src/engine/money (D-16).

begin;
create extension if not exists pgtap with schema extensions;

select extensions.plan(50);

select extensions.is(public.div_half_up(5::numeric, 2::numeric), 3::bigint, 'halfUp 5/2');
select extensions.is(public.div_half_up(-5::numeric, 2::numeric), -3::bigint, 'halfUp -5/2');
select extensions.is(public.div_half_up(3::numeric, 2::numeric), 2::bigint, 'halfUp 3/2');
select extensions.is(public.div_half_up(7::numeric, 2::numeric), 4::bigint, 'halfUp 7/2');
select extensions.is(public.div_half_up(1::numeric, 3::numeric), 0::bigint, 'halfUp 1/3');
select extensions.is(public.div_half_up(2::numeric, 3::numeric), 1::bigint, 'halfUp 2/3');
select extensions.is(public.div_half_up(-1::numeric, 3::numeric), 0::bigint, 'halfUp -1/3');
select extensions.is(public.div_half_up(-2::numeric, 3::numeric), -1::bigint, 'halfUp -2/3');
select extensions.is(public.div_half_up(0::numeric, 7::numeric), 0::bigint, 'halfUp 0/7');
select extensions.is(public.div_half_up(49::numeric, 100::numeric), 0::bigint, 'halfUp 49/100');
select extensions.is(public.div_half_up(50::numeric, 100::numeric), 1::bigint, 'halfUp 50/100');
select extensions.is(public.div_half_up(-50::numeric, 100::numeric), -1::bigint, 'halfUp -50/100');
select extensions.is(public.div_half_up(149::numeric, 100::numeric), 1::bigint, 'halfUp 149/100');
select extensions.is(public.div_half_up(150::numeric, 100::numeric), 2::bigint, 'halfUp 150/100');
select extensions.is(public.div_half_up(250::numeric, 100::numeric), 3::bigint, 'halfUp 250/100');
select extensions.is(public.div_half_up(-250::numeric, 100::numeric), -3::bigint, 'halfUp -250/100');
select extensions.is(public.convert_minor(1000::bigint, '1.1483'::numeric, 2, '180.7'::numeric, 0), 1574::bigint, 'convert: USD 10.00 to JPY');
select extensions.is(public.convert_minor(1000::bigint, '180.7'::numeric, 0, '1.1483'::numeric, 2), 635::bigint, 'convert: JPY 1000 to USD');
select extensions.is(public.convert_minor(1000::bigint, '0.3512'::numeric, 3, '1'::numeric, 2), 285::bigint, 'convert: KWD 1.000 to EUR');
select extensions.is(public.convert_minor(12345::bigint, '1'::numeric, 2, '1'::numeric, 2), 12345::bigint, 'convert: EUR same currency');
select extensions.is(public.convert_minor(5::bigint, '2'::numeric, 2, '1'::numeric, 2), 3::bigint, 'convert: exact tie 2.5 rounds up');
select extensions.is(public.convert_minor(-5::bigint, '2'::numeric, 2, '1'::numeric, 2), -3::bigint, 'convert: exact tie -2.5 rounds away from zero');
select extensions.is(public.convert_minor(2::bigint, '4'::numeric, 2, '1'::numeric, 2), 1::bigint, 'convert: tie 0.5');
select extensions.is(public.convert_minor(6::bigint, '4'::numeric, 2, '1'::numeric, 2), 2::bigint, 'convert: tie 1.5');
select extensions.is(public.convert_minor(10::bigint, '4'::numeric, 2, '1'::numeric, 2), 3::bigint, 'convert: tie 2.5 (banker''s would give 2)');
select extensions.is(public.convert_minor(-1000::bigint, '1.1483'::numeric, 2, '180.7'::numeric, 0), -1574::bigint, 'convert: negative USD to JPY');
select extensions.is(public.convert_minor(0::bigint, '1.1483'::numeric, 2, '180.7'::numeric, 0), 0::bigint, 'convert: zero');
select extensions.is(public.convert_minor(10::bigint, '0.45932'::numeric, 0, '1.1483'::numeric, 2), 2500::bigint, 'convert: custom GLD 10 (0dp, 1 GLD = 2.5 USD) to USD');
select extensions.is(public.convert_minor(2000::bigint, '170'::numeric, 0, '1.15'::numeric, 2), 1353::bigint, 'convert: JPY 2000 to USD at 09-18 rates');
select extensions.is(public.convert_minor(1000::bigint, '170'::numeric, 0, '1.15'::numeric, 2), 676::bigint, 'convert: JPY 1000 to USD at 09-18 rates');
select extensions.is(public.custom_per_eur('1.1483'::numeric, '2.5'::numeric)::text, '0.4593200000', 'customPerEur: USD ref, 1 unit = 2.5 USD');
select extensions.is(public.custom_per_eur('1'::numeric, '3'::numeric)::text, '0.3333333333', 'customPerEur: 1/3 truncates below half');
select extensions.is(public.custom_per_eur('2'::numeric, '3'::numeric)::text, '0.6666666667', 'customPerEur: 2/3 rounds up');
select extensions.is(public.cross_rate('1.1483'::numeric, '180.7'::numeric)::text, '157.3630584342', 'crossRate: 1 USD in JPY');
select extensions.is(public.cross_rate('180.7'::numeric, '1.1483'::numeric)::text, '0.0063547316', 'crossRate: 1 JPY in USD');
select extensions.is(public.currency_exponent('JPY', null), 0, 'exponent JPY');
select extensions.is(public.currency_exponent('KRW', null), 0, 'exponent KRW');
select extensions.is(public.currency_exponent('VND', null), 0, 'exponent VND');
select extensions.is(public.currency_exponent('ISK', null), 0, 'exponent ISK');
select extensions.is(public.currency_exponent('CLP', null), 0, 'exponent CLP');
select extensions.is(public.currency_exponent('KWD', null), 3, 'exponent KWD');
select extensions.is(public.currency_exponent('BHD', null), 3, 'exponent BHD');
select extensions.is(public.currency_exponent('OMR', null), 3, 'exponent OMR');
select extensions.is(public.currency_exponent('JOD', null), 3, 'exponent JOD');
select extensions.is(public.currency_exponent('TND', null), 3, 'exponent TND');
select extensions.is(public.currency_exponent('CLF', null), 4, 'exponent CLF');
select extensions.is(public.currency_exponent('USD', null), 2, 'exponent USD');
select extensions.is(public.currency_exponent('EUR', null), 2, 'exponent EUR');
select extensions.is(public.currency_exponent('GBP', null), 2, 'exponent GBP');
select extensions.is(public.currency_exponent('CAD', null), 2, 'exponent CAD');

select * from extensions.finish();
rollback;
