/**
 * Built-in ISO 4217 currency list (02-DECISION-fx-on-demand.md, item 1). The currency picker
 * reads this list instead of the server `currencies` table, so it works with an empty
 * `fx_rates` table, an empty `currencies` table and on first launch offline.
 *
 * Pure data: no imports. Exponents are literals, proven equal to `currencyExponent(code)` by
 * the isoCurrencies test (MON-13), and every code is proven to be in the server's active
 * ISO 4217 block by a parity test under src/data.
 *
 * Source: Frankfurter v2 `GET https://api.frankfurter.dev/v2/currencies`, fetched on the
 * snapshot date below. Inclusion rule: ISO 4217 active circulating currencies (no fund/unit
 * codes BOV CHE CHW CLF COU MXV USN UYI UYW; no metal/SDR/testing codes XAG XAU XBA XBB XBC
 * XBD XDR XPD XPT XSU XTS XUA XXX) that Frankfurter can price (end_date null or within 30 days
 * of the snapshot date). A code Frankfurter cannot price would stay "rate pending" forever.
 * Not in the active ISO block, so left out: ANG, CMD, CNH, GGP, IMP, JEP.
 *
 * Refresh at an app release: re-fetch the endpoint, re-apply the rule, update the snapshot
 * date, keep the array sorted by code, and run the engine/money and src/data tests.
 */
export interface IsoCurrency {
  readonly code: string;
  readonly name: string;
  readonly symbol: string | null;
  readonly exponent: number;
}

export const ISO_CURRENCY_LIST_AS_OF = '2026-10-07';

export const ISO_CURRENCIES: readonly IsoCurrency[] = Object.freeze([
  {
    code: 'AED',
    name: 'United Arab Emirates Dirham',
    symbol: 'د.إ',
    exponent: 2,
  },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', exponent: 2 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', exponent: 2 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', exponent: 2 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', exponent: 2 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', exponent: 2 },
  { code: 'AUD', name: 'Australian Dollar', symbol: '$', exponent: 2 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', exponent: 2 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', exponent: 2 },
  {
    code: 'BAM',
    name: 'Bosnia and Herzegovina Convertible Mark',
    symbol: 'КМ',
    exponent: 2,
  },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', exponent: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', exponent: 2 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'د.ب', exponent: 3 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'Fr', exponent: 0 },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$', exponent: 2 },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', exponent: 2 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', exponent: 2 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', exponent: 2 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', exponent: 2 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', exponent: 2 },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', exponent: 2 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', exponent: 2 },
  { code: 'BZD', name: 'Belize Dollar', symbol: '$', exponent: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: '$', exponent: 2 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'Fr', exponent: 2 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', exponent: 2 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', exponent: 0 },
  { code: 'CNY', name: 'Chinese Renminbi Yuan', symbol: '¥', exponent: 2 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', exponent: 2 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', exponent: 2 },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', exponent: 2 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', exponent: 2 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', exponent: 2 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', exponent: 0 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr.', exponent: 2 },
  { code: 'DOP', name: 'Dominican Peso', symbol: '$', exponent: 2 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', exponent: 2 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'ج.م', exponent: 2 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', exponent: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', exponent: 2 },
  { code: 'EUR', name: 'Euro', symbol: '€', exponent: 2 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', exponent: 2 },
  { code: 'FKP', name: 'Falkland Pound', symbol: '£', exponent: 2 },
  { code: 'GBP', name: 'British Pound', symbol: '£', exponent: 2 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', exponent: 2 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', exponent: 2 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', exponent: 2 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', exponent: 2 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'Fr', exponent: 0 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', exponent: 2 },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$', exponent: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', exponent: 2 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', exponent: 2 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', exponent: 2 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', exponent: 2 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', exponent: 2 },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', exponent: 2 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', exponent: 2 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', exponent: 3 },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', exponent: 2 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr.', exponent: 0 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: '$', exponent: 2 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', exponent: 3 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', exponent: 0 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', exponent: 2 },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'som', exponent: 2 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', exponent: 2 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'Fr', exponent: 0 },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', exponent: 2 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', exponent: 0 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', exponent: 3 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', exponent: 2 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', exponent: 2 },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', exponent: 2 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', exponent: 2 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', exponent: 2 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', exponent: 2 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', exponent: 2 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', exponent: 3 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', exponent: 2 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', exponent: 2 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', exponent: 2 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', exponent: 2 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', exponent: 2 },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', exponent: 2 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'P', exponent: 2 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', exponent: 2 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', exponent: 2 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR', exponent: 2 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', exponent: 2 },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', exponent: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', exponent: 2 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MTn', exponent: 2 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', exponent: 2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', exponent: 2 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', exponent: 2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', exponent: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs.', exponent: 2 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', exponent: 2 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', exponent: 3 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', exponent: 2 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', exponent: 2 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', exponent: 2 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', exponent: 2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', exponent: 2 },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', exponent: 2 },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', exponent: 0 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', exponent: 2 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'Lei', exponent: 2 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD', exponent: 2 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', exponent: 2 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', exponent: 0 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', exponent: 2 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', exponent: 2 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', exponent: 2 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: '£', exponent: 2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', exponent: 2 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: '$', exponent: 2 },
  { code: 'SHP', name: 'Saint Helenian Pound', symbol: '£', exponent: 2 },
  { code: 'SLE', name: 'New Leone', symbol: 'Le', exponent: 2 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', exponent: 2 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', exponent: 2 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', exponent: 2 },
  {
    code: 'STN',
    name: 'São Tomé and Príncipe Second Dobra',
    symbol: 'Db',
    exponent: 2,
  },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: '₡', exponent: 2 },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S', exponent: 2 },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', exponent: 2 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', exponent: 2 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', exponent: 2 },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', exponent: 2 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', exponent: 3 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', exponent: 2 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', exponent: 2 },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$', exponent: 2 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: '$', exponent: 2 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'Sh', exponent: 2 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', exponent: 2 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', exponent: 0 },
  { code: 'USD', name: 'United States Dollar', symbol: '$', exponent: 2 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', exponent: 2 },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: "so'm", exponent: 2 },
  {
    code: 'VES',
    name: 'Venezuelan Bolívar Soberano',
    symbol: 'Bs',
    exponent: 2,
  },
  { code: 'VND', name: 'Vietnamese Đồng', symbol: '₫', exponent: 0 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt', exponent: 0 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'T', exponent: 2 },
  {
    code: 'XAF',
    name: 'Central African CFA Franc',
    symbol: 'CFA',
    exponent: 0,
  },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', exponent: 2 },
  { code: 'XCG', name: 'Caribbean Guilder', symbol: 'Cg', exponent: 2 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr', exponent: 0 },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', exponent: 0 },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', exponent: 2 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', exponent: 2 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'K', exponent: 2 },
  { code: 'ZWG', name: 'Zimbabwe Gold', symbol: 'ZiG', exponent: 2 },
]);

const BY_CODE: ReadonlyMap<string, IsoCurrency> = new Map(ISO_CURRENCIES.map((c) => [c.code, c]));

/** Case-sensitive lookup of a built-in currency by its ISO code. */
export function isoCurrency(code: string): IsoCurrency | undefined {
  return BY_CODE.get(code);
}
